version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - JWT_SECRET=s3cr3tK3yG3n3r4t3dStr1ng==
    ports:
      - "4000:4000"
    networks:
      - mynetwork

volumes:
  postgres_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
