version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

volumes:
  postgres_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
