# Stage 1: Build Stage
FROM node:20 AS build

# Set working directory
WORKDIR /apps/server

# Install pnpm globally
RUN npm install -g pnpm

# Copy client package.json and pnpm-lock.yaml from the root directory
COPY package.json ./

# Install client dependencies
RUN pnpm install

# Copy the entire client project
COPY . .

# Build the Next.js app
RUN pnpm build:server

# Stage 2: Production Stage
FROM node:20

# Set working directory
WORKDIR /apps/server

# Copy only necessary files from the build stage
COPY --from=build /apps/server/node_modules /apps/server/node_modules
COPY --from=build /apps/server/apps/server/node_modules /apps/server/apps/server/node_modules
COPY --from=build /apps/server/apps/server/dist /apps/server/apps/server/dist

CMD ["sh", "-c", "cd apps/server npx sequelize-cli db:migrate && node /apps/server/apps/server/dist/main.js"]